; Floki configuration file
; This file defines the configuration parameters for Floki, including network interfaces, management settings, and RTP relay port ranges. 
; Adjust the values as needed for your specific environment and requirements.

; General settings for Floki.
[general]
manager_ip=0.0.0.0.     ; Defines the IP address on which Floki will listen for management commands.
manager_port=2223       ; Defines the port on which Floki will listen for management commands.
rtp_port_min=16384      ; Defines the minimum port number for RTP relay. Default is 16384.
rtp_port_max=32767      ; Defines the maximum port number for RTP relay. Default is 32767.
cleanup_on_start=true   ; If true, Floki will attempt to clean up any existing RTP forwarding rules on startup. This can help ensure a clean state if Floki was previously running or if there were unexpected shutdowns.
enable_ip_forward=true  ; If true, Floki will enable the Linux Kernel IP forwarding.
auto_manage_filter=true ; If true, Floki will automatically manage firewall rules for RTP traffic (INPUT and FORWARD chains).
log_level=info          ; Defines the logging level. Options are: debug, info, warn, error.

; Network interface configurations.
; Define the IP addresses for the network interfaces that Floki will use. You can add more interfaces as needed by following the same format.
; Names are for reference only and do not affect functionality, any strings can be used.
; The IP addresses should correspond to the actual network interfaces on the machine where Floki is running.
[wan]
ip=192.168.0.199

[lan]
ip=192.168.56.105

;[lan2]
;ip=172.16.0.1

;[lanN]
;ip=10.0.0.1